custom_resource_pack_link: false
# Make sure that when you open the link, your computer directly downloads the file, else it won't work.
# resource_pack_link: "https://www.website.com/yourfile"
prismarineTools: true
stoneToolsVariants: true
woodToolsVariants: true
concretePowderToConcreteCraftWithBucket: true