custom_resource_pack_link: false
# Make sure that when you open the link, your computer directly downloads the file, else it won't work.
# resource_pack_link: "https://www.website.com/yourfile"
weight_modifier: true
weight_modifier_in_creative: true
weight_gliding_modifier: 0
# weight_gliding_modifier: 0.0025
# Do not put high values for weight_gliding_modifier. You'll understand if you test it.
lossless_mending_system: true
prismarineTools: true
stoneToolsVariants: true
woodToolsVariants: true
craftable_chainmail_armor_with_chains: true
ender_pearl_cooldown: 20
# Cooldown is in ticks. In vanilla minecraft, the ender pearl cooldown is 1 second, = 20 ticks.
concrete_powder_to_concrete_craft_with_bucket: true
concrete_powder_interacts_with_water: false
fire_aspect_pickaxes_drop_molten_material: false
fire_aspect_pickaxe_drops_exp: true
chance_of_dropping_molten_ore_by_fire_aspect_level: 0.5 # Level 1: 50%, Level 2: 100%, etc
# You have to change enchantments.yml to be able to enchant pickaxes with fire aspect if you want the two previous options.
boost_quartz_drop: true
farmland_not_breaking_on_jump: true
player_velocity_on_attack_modifier: 0.0
# Player speed (relative to the damaged entity) is multiplied by this constant and added to the damage total.
thorns_durability_modifier: 2
seconds_before_afk: 60
sitting_on_blocks: false