package fr.phlayne.imagicube.item;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.bukkit.Material;

public enum Tools implements Tool {

	PICKAXE("pickaxe", Material.OBSIDIAN, Material.ENDER_CHEST, Material.ANVIL, Material.COAL_BLOCK,
			Material.DIAMOND_BLOCK, Material.EMERALD_BLOCK, Material.IRON_BLOCK, Material.REDSTONE_BLOCK,
			Material.ENCHANTING_TABLE, Material.IRON_BARS, Material.IRON_DOOR, Material.SPAWNER, Material.DISPENSER,
			Material.DROPPER, Material.FURNACE, Material.GOLD_BLOCK, Material.COAL_ORE, Material.DIAMOND_ORE,
			Material.EMERALD_ORE, Material.END_STONE, Material.GOLD_ORE, Material.HOPPER, Material.IRON_ORE,
			Material.LAPIS_BLOCK, Material.LAPIS_ORE, Material.NETHER_QUARTZ_ORE, Material.REDSTONE_ORE,
			Material.BRICK_STAIRS, Material.BRICKS, Material.CAULDRON, Material.COBBLESTONE, Material.STONE_STAIRS,
			Material.COBBLESTONE_WALL, Material.MOSSY_COBBLESTONE, Material.NETHER_BRICK, Material.NETHER_BRICK_FENCE,
			Material.NETHER_BRICK_STAIRS, Material.STONE_SLAB, Material.ANDESITE_SLAB, Material.COBBLESTONE_SLAB,
			Material.CUT_RED_SANDSTONE_SLAB, Material.CUT_SANDSTONE_SLAB, Material.DARK_PRISMARINE_SLAB,
			Material.DIORITE_SLAB, Material.END_STONE_BRICK_SLAB, Material.GRANITE_SLAB,
			Material.MOSSY_COBBLESTONE_SLAB, Material.MOSSY_STONE_BRICK_SLAB, Material.NETHER_BRICK_SLAB,
			Material.POLISHED_ANDESITE_SLAB, Material.POLISHED_DIORITE_SLAB, Material.POLISHED_GRANITE_SLAB,
			Material.PRISMARINE_BRICK_SLAB, Material.PRISMARINE_SLAB, Material.PURPUR_SLAB, Material.QUARTZ_SLAB,
			Material.RED_NETHER_BRICK_SLAB, Material.RED_SANDSTONE_SLAB, Material.SANDSTONE_SLAB,
			Material.SMOOTH_QUARTZ_SLAB, Material.SMOOTH_RED_SANDSTONE_SLAB, Material.SMOOTH_SANDSTONE_SLAB,
			Material.SMOOTH_STONE_SLAB, Material.STONE_BRICK_SLAB, Material.STONE_SLAB, Material.ANDESITE,
			Material.DIORITE, Material.GRANITE, Material.POLISHED_ANDESITE, Material.POLISHED_DIORITE,
			Material.POLISHED_GRANITE, Material.PRISMARINE, Material.DARK_PRISMARINE, Material.PRISMARINE_BRICKS,
			Material.STONE, Material.STONE_BRICKS, Material.STONE_BRICK_STAIRS, Material.TERRACOTTA,
			Material.WHITE_TERRACOTTA, Material.ORANGE_TERRACOTTA, Material.MAGENTA_TERRACOTTA,
			Material.LIGHT_BLUE_TERRACOTTA, Material.YELLOW_TERRACOTTA, Material.LIME_TERRACOTTA,
			Material.PINK_TERRACOTTA, Material.GRAY_TERRACOTTA, Material.LIGHT_GRAY_TERRACOTTA,
			Material.CYAN_TERRACOTTA, Material.PURPLE_TERRACOTTA, Material.BLUE_TERRACOTTA, Material.BROWN_TERRACOTTA,
			Material.GREEN_TERRACOTTA, Material.RED_TERRACOTTA, Material.BLACK_TERRACOTTA, Material.QUARTZ_BLOCK,
			Material.QUARTZ_STAIRS, Material.SANDSTONE, Material.RAIL, Material.ACTIVATOR_RAIL, Material.DETECTOR_RAIL,
			Material.POWERED_RAIL, Material.BREWING_STAND, Material.ICE, Material.PACKED_ICE, Material.BLUE_ICE,
			Material.STONE_PRESSURE_PLATE, Material.HEAVY_WEIGHTED_PRESSURE_PLATE,
			Material.LIGHT_WEIGHTED_PRESSURE_PLATE, Material.NETHERRACK, Material.WHITE_CONCRETE,
			Material.ORANGE_CONCRETE, Material.MAGENTA_CONCRETE, Material.LIGHT_BLUE_CONCRETE, Material.YELLOW_CONCRETE,
			Material.LIME_CONCRETE, Material.PINK_CONCRETE, Material.GRAY_CONCRETE, Material.LIGHT_GRAY_CONCRETE,
			Material.CYAN_CONCRETE, Material.PURPLE_CONCRETE, Material.BLUE_CONCRETE, Material.BROWN_CONCRETE,
			Material.GREEN_CONCRETE, Material.RED_CONCRETE, Material.BLACK_CONCRETE, Material.CRIMSON_NYLIUM,
			Material.WARPED_NYLIUM, Material.CRYING_OBSIDIAN, Material.RESPAWN_ANCHOR, Material.ANCIENT_DEBRIS,
			Material.NETHERITE_BLOCK, Material.LODESTONE, Material.BASALT, Material.POLISHED_BASALT,
			Material.NETHER_GOLD_ORE, Material.GILDED_BLACKSTONE, Material.BLACKSTONE, Material.BLACKSTONE_SLAB,
			Material.BLACKSTONE_STAIRS, Material.BLACKSTONE_WALL, Material.POLISHED_BLACKSTONE,
			Material.POLISHED_BLACKSTONE_SLAB, Material.POLISHED_BLACKSTONE_STAIRS, Material.POLISHED_BLACKSTONE_WALL,
			Material.POLISHED_BLACKSTONE_BRICKS, Material.POLISHED_BLACKSTONE_BRICK_SLAB,
			Material.POLISHED_BLACKSTONE_BRICK_STAIRS, Material.POLISHED_BLACKSTONE_BRICK_WALL,
			Material.POLISHED_BLACKSTONE_BUTTON, Material.POLISHED_BLACKSTONE_PRESSURE_PLATE,
			Material.CHISELED_POLISHED_BLACKSTONE, Material.CRACKED_POLISHED_BLACKSTONE_BRICKS,
			Material.CRACKED_NETHER_BRICKS, Material.QUARTZ_BRICKS, Material.CHISELED_NETHER_BRICKS, Material.CHAIN,
			Material.SOUL_LANTERN, Material.LANTERN, Material.SMALL_AMETHYST_BUD, Material.MEDIUM_AMETHYST_BUD,
			Material.LARGE_AMETHYST_BUD, Material.AMETHYST_CLUSTER, Material.AMETHYST_BLOCK, Material.RAW_COPPER_BLOCK,
			Material.COPPER_BLOCK, Material.CUT_COPPER, Material.CUT_COPPER_STAIRS, Material.CUT_COPPER_SLAB,
			Material.WAXED_COPPER_BLOCK, Material.WAXED_CUT_COPPER, Material.CUT_COPPER_STAIRS,
			Material.CUT_COPPER_SLAB, Material.EXPOSED_COPPER, Material.EXPOSED_CUT_COPPER,
			Material.EXPOSED_CUT_COPPER_STAIRS, Material.EXPOSED_CUT_COPPER_SLAB, Material.WAXED_EXPOSED_COPPER,
			Material.WAXED_EXPOSED_CUT_COPPER, Material.WAXED_EXPOSED_CUT_COPPER_STAIRS,
			Material.WAXED_EXPOSED_CUT_COPPER_SLAB, Material.WEATHERED_COPPER, Material.WEATHERED_CUT_COPPER,
			Material.WEATHERED_CUT_COPPER_STAIRS, Material.WEATHERED_CUT_COPPER_SLAB, Material.WAXED_WEATHERED_COPPER,
			Material.WAXED_WEATHERED_CUT_COPPER, Material.WAXED_WEATHERED_CUT_COPPER_STAIRS,
			Material.WAXED_WEATHERED_CUT_COPPER_SLAB, Material.OXIDIZED_COPPER, Material.OXIDIZED_CUT_COPPER,
			Material.OXIDIZED_CUT_COPPER_STAIRS, Material.OXIDIZED_CUT_COPPER_SLAB, Material.WAXED_OXIDIZED_COPPER,
			Material.WAXED_OXIDIZED_CUT_COPPER, Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS,
			Material.WAXED_OXIDIZED_CUT_COPPER_SLAB, Material.RAW_GOLD_BLOCK, Material.RAW_IRON_BLOCK,
			Material.BUDDING_AMETHYST, Material.CALCITE, Material.SMOOTH_BASALT, Material.COPPER_ORE,
			Material.DEEPSLATE, Material.DEEPSLATE_BRICK_SLAB, Material.DEEPSLATE_BRICK_STAIRS,
			Material.DEEPSLATE_BRICK_WALL, Material.DEEPSLATE_BRICKS, Material.DEEPSLATE_COAL_ORE,
			Material.DEEPSLATE_DIAMOND_ORE, Material.DEEPSLATE_EMERALD_ORE, Material.DEEPSLATE_GOLD_ORE,
			Material.DEEPSLATE_IRON_ORE, Material.DEEPSLATE_LAPIS_ORE, Material.DEEPSLATE_REDSTONE_ORE,
			Material.DEEPSLATE_TILE_SLAB, Material.DEEPSLATE_TILE_STAIRS, Material.DEEPSLATE_TILE_WALL,
			Material.DEEPSLATE_TILES, Material.CHISELED_DEEPSLATE, Material.COBBLED_DEEPSLATE,
			Material.COBBLED_DEEPSLATE_SLAB, Material.COBBLED_DEEPSLATE_STAIRS, Material.COBBLED_DEEPSLATE_WALL,
			Material.CRACKED_DEEPSLATE_BRICKS, Material.CRACKED_DEEPSLATE_TILES, Material.POLISHED_DEEPSLATE,
			Material.POLISHED_DEEPSLATE_SLAB, Material.POLISHED_DEEPSLATE_STAIRS, Material.POLISHED_DEEPSLATE_WALL,
			Material.DRIPSTONE_BLOCK, Material.POINTED_DRIPSTONE, Material.LIGHTNING_ROD, Material.TUFF),
	AXE("axe", Material.OAK_DOOR, Material.SPRUCE_DOOR, Material.BIRCH_DOOR, Material.JUNGLE_DOOR, Material.ACACIA_DOOR,
			Material.DARK_OAK_DOOR, Material.ACACIA_TRAPDOOR, Material.BIRCH_TRAPDOOR, Material.DARK_OAK_TRAPDOOR,
			Material.JUNGLE_TRAPDOOR, Material.OAK_TRAPDOOR, Material.SPRUCE_TRAPDOOR, Material.CHEST,
			Material.CRAFTING_TABLE, Material.ACACIA_FENCE, Material.BIRCH_FENCE, Material.DARK_OAK_FENCE,
			Material.JUNGLE_FENCE, Material.OAK_FENCE, Material.SPRUCE_FENCE, Material.ACACIA_FENCE_GATE,
			Material.BIRCH_FENCE_GATE, Material.DARK_OAK_FENCE_GATE, Material.JUNGLE_FENCE_GATE,
			Material.OAK_FENCE_GATE, Material.SPRUCE_FENCE_GATE, Material.JUKEBOX, Material.ACACIA_LOG,
			Material.BIRCH_LOG, Material.DARK_OAK_LOG, Material.JUNGLE_LOG, Material.OAK_LOG, Material.SPRUCE_LOG,
			Material.STRIPPED_ACACIA_LOG, Material.STRIPPED_BIRCH_LOG, Material.STRIPPED_DARK_OAK_LOG,
			Material.STRIPPED_JUNGLE_LOG, Material.STRIPPED_OAK_LOG, Material.STRIPPED_SPRUCE_LOG,
			Material.ACACIA_PLANKS, Material.BIRCH_PLANKS, Material.DARK_OAK_PLANKS, Material.JUNGLE_PLANKS,
			Material.OAK_PLANKS, Material.SPRUCE_PLANKS, Material.ACACIA_SLAB, Material.BIRCH_SLAB,
			Material.DARK_OAK_SLAB, Material.JUNGLE_SLAB, Material.OAK_SLAB, Material.SPRUCE_SLAB,
			Material.ACACIA_STAIRS, Material.BIRCH_STAIRS, Material.DARK_OAK_STAIRS, Material.JUNGLE_STAIRS,
			Material.OAK_STAIRS, Material.SPRUCE_STAIRS, Material.BOOKSHELF, Material.PUMPKIN, Material.CARVED_PUMPKIN,
			Material.MELON, Material.ACACIA_SIGN, Material.BIRCH_SIGN, Material.DARK_OAK_SIGN, Material.JUNGLE_SIGN,
			Material.OAK_SIGN, Material.SPRUCE_SIGN, Material.ACACIA_WALL_SIGN, Material.BIRCH_WALL_SIGN,
			Material.DARK_OAK_WALL_SIGN, Material.JUNGLE_WALL_SIGN, Material.OAK_WALL_SIGN, Material.SPRUCE_WALL_SIGN,
			Material.NOTE_BLOCK, Material.ACACIA_PRESSURE_PLATE, Material.BIRCH_PRESSURE_PLATE,
			Material.DARK_OAK_PRESSURE_PLATE, Material.JUNGLE_PRESSURE_PLATE, Material.OAK_PRESSURE_PLATE,
			Material.SPRUCE_PRESSURE_PLATE, Material.ACACIA_BUTTON, Material.BIRCH_BUTTON, Material.DARK_OAK_BUTTON,
			Material.JUNGLE_BUTTON, Material.OAK_BUTTON, Material.SPRUCE_BUTTON, Material.LADDER, Material.COCOA,
			Material.DAYLIGHT_DETECTOR, Material.BROWN_MUSHROOM_BLOCK, Material.RED_MUSHROOM_BLOCK,
			Material.MUSHROOM_STEM, Material.VINE, Material.BEE_NEST, Material.BEEHIVE, Material.CRIMSON_PLANKS,
			Material.CRIMSON_STEM, Material.STRIPPED_CRIMSON_STEM, Material.CRIMSON_HYPHAE, Material.CRIMSON_SLAB,
			Material.STRIPPED_CRIMSON_HYPHAE, Material.CRIMSON_PRESSURE_PLATE, Material.CRIMSON_FENCE,
			Material.CRIMSON_FENCE_GATE, Material.CRIMSON_TRAPDOOR, Material.CRIMSON_STAIRS, Material.CRIMSON_BUTTON,
			Material.CRIMSON_SIGN, Material.CRIMSON_WALL_SIGN, Material.CRIMSON_DOOR, Material.WARPED_PLANKS,
			Material.WARPED_STEM, Material.STRIPPED_WARPED_STEM, Material.WARPED_HYPHAE, Material.WARPED_SLAB,
			Material.STRIPPED_WARPED_HYPHAE, Material.WARPED_PRESSURE_PLATE, Material.WARPED_FENCE,
			Material.WARPED_FENCE_GATE, Material.WARPED_TRAPDOOR, Material.WARPED_STAIRS, Material.WARPED_BUTTON,
			Material.WARPED_SIGN, Material.WARPED_WALL_SIGN, Material.WARPED_DOOR, Material.SOUL_CAMPFIRE,
			Material.CAMPFIRE),
	SHOVEL("shovel", Material.GRAVEL, Material.FARMLAND, Material.DIRT_PATH, Material.CLAY, Material.GRASS_BLOCK,
			Material.MYCELIUM, Material.PODZOL, Material.DIRT, Material.COARSE_DIRT, Material.SAND, Material.RED_SAND,
			Material.SOUL_SAND, Material.SNOW_BLOCK, Material.SNOW, Material.WHITE_CONCRETE_POWDER,
			Material.ORANGE_CONCRETE_POWDER, Material.MAGENTA_CONCRETE_POWDER, Material.LIGHT_BLUE_CONCRETE_POWDER,
			Material.YELLOW_CONCRETE_POWDER, Material.LIME_CONCRETE_POWDER, Material.PINK_CONCRETE_POWDER,
			Material.GRAY_CONCRETE_POWDER, Material.LIGHT_GRAY_CONCRETE_POWDER, Material.CYAN_CONCRETE_POWDER,
			Material.PURPLE_CONCRETE_POWDER, Material.BLUE_CONCRETE_POWDER, Material.BROWN_CONCRETE_POWDER,
			Material.GREEN_CONCRETE_POWDER, Material.RED_CONCRETE_POWDER, Material.BLACK_CONCRETE_POWDER),
	HOE("hoe", Material.OAK_LEAVES, Material.SPRUCE_LEAVES, Material.BIRCH_LEAVES, Material.JUNGLE_LEAVES,
			Material.ACACIA_LEAVES, Material.DARK_OAK_LEAVES, Material.NETHER_WART_BLOCK, Material.WARPED_WART_BLOCK,
			Material.HAY_BLOCK, Material.TARGET, Material.DRIED_KELP_BLOCK, Material.SPONGE, Material.WET_SPONGE,
			Material.SHROOMLIGHT, Material.MOSS_BLOCK),
	FLINTANDSTEEL("flint_and_steel"), FISHING_ROD("fishing_rod"),
	SHEARS("shears", Material.ACACIA_LEAVES, Material.BIRCH_LEAVES, Material.DARK_OAK_LEAVES, Material.JUNGLE_LEAVES,
			Material.OAK_LEAVES, Material.SPRUCE_LEAVES, Material.COBWEB, Material.STRING, Material.VINE,
			Material.TALL_GRASS, Material.TALL_SEAGRASS, Material.DEAD_BUSH, Material.NETHER_SPROUTS),
	SCYTHE("scythe", HOE.getToolBlocks(), Material.CRIMSON_ROOTS, Material.WARPED_ROOTS, Material.LARGE_FERN,
			Material.ROSE_BUSH, Material.SEAGRASS, Material.FARMLAND),
	SWORD("sword", Material.COBWEB, Material.JACK_O_LANTERN, Material.MELON, Material.PUMPKIN, Material.COCOA,
			Material.ACACIA_LEAVES, Material.BIRCH_LEAVES, Material.DARK_OAK_LEAVES, Material.JUNGLE_LEAVES,
			Material.OAK_LEAVES, Material.SPRUCE_LEAVES, Material.VINE, Material.HAY_BLOCK);

	// Add azalea leaves and other 1.18 blocks?

	private String name;
	private List<Material> toolBlocks;

	Tools(String name, Material... toolBlocks) {
		this.name = name;
		this.toolBlocks = new ArrayList<Material>(Arrays.asList(toolBlocks));
	}

	Tools(String name, List<Material> baseToolBlocks, Material... toolBlocks) {
		this.name = name;
		this.toolBlocks = baseToolBlocks;
		this.toolBlocks.addAll(Arrays.asList(toolBlocks));
	}

	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public boolean canDamage(Material material) {
		return toolBlocks.contains(material);
	}

	public List<Material> getToolBlocks() {
		return this.toolBlocks;
	}

}
